# Generated by Django 3.0.8 on 2020-07-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=200, null=True)),
                ('partner_name', models.CharField(max_length=200, null=True)),
                ('my_star', models.CharField(max_length=100, null=True)),
                ('partner_star', models.EmailField(max_length=100, null=True)),
            ],
        ),
    ]
