# Generated by Django 3.0.8 on 2020-07-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200714_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='your_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='your_partner_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='your_partner_star',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='your_star',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
