# Generated by Django 3.0.8 on 2020-07-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200714_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='feel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
