# Generated by Django 3.0.8 on 2020-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_contact_feel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='rate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
