# Generated by Django 3.0.8 on 2020-07-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_contact_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_name', models.CharField(max_length=20, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='rate',
        ),
    ]
