# Generated by Django 3.0.8 on 2020-07-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200715_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
