# Generated by Django 3.0.8 on 2020-07-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_delete_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
